import { KITTY_ANIMATED_SHADERS } from '../kitty-config.js';
import { kittyCompat, convertPaper } from './kitty-compat.js';
import { textureSource, textureAssets } from './kitty-texture.js';

const INLINE_IMAGE_SHADERS = new Set(['gem-smoke', 'heatmap', 'liquid-metal']);

function number(value) {
  if (!Number.isFinite(value))
    throw new Error('Invalid Kitty shader parameter.');
  return Number.isInteger(value) ? `${value}.0` : String(value);
}

function literal(value, type) {
  if (Array.isArray(value)) return `${type}(${value.map(number).join(', ')})`;
  return number(value);
}

// Every source is pinned and covered by the Kitty compilation fixtures.
export function kittyShader(preset, glsl, uniforms, fps = 30, textures = []) {
  if (!KITTY_ANIMATED_SHADERS.has(preset.shader))
    throw new Error('Unknown Paper shader.');
  const constants = [];
  const dynamic = new Set(['u_time', 'u_resolution']);
  const values = {
    ...uniforms,
    u_pixelRatio: 1,
    u_imageAspectRatio:
      textures.find((t) => t.name === 'u_image')?.aspectRatio ?? 1,
  };
  // These single-texture shaders can read their paletted pixels directly.
  // A separate atlas pass can become visible during a Kitty reload.
  const inlineTexture =
    textures.length === 1 &&
    (textures[0].name === 'u_noiseTexture' ||
      INLINE_IMAGE_SHADERS.has(preset.shader));
  const assets = inlineTexture ? [] : textureAssets(textures);
  let body = convertPaper(glsl)
    .replace(
      /^uniform (float[234]?|bool|int) (\w+)(?:\[(\d+)\])?;$/gm,
      (_line, type, name, count) => {
        if (dynamic.has(name)) return '';
        const value = values[name];
        if (count) {
          const items = Array.from({ length: Number(count) }, (_, i) =>
            literal(value[i] ?? [0, 0, 0, 0], type),
          );
          constants.push(
            `static const ${type} ${name}[${count}] = {${items.join(', ')}};`,
          );
        } else if (type === 'bool')
          constants.push(`static const bool ${name} = ${Boolean(value)};`);
        else if (type === 'int')
          constants.push(
            `static const int ${name} = ${textures.findIndex((t) => t.name === name)};`,
          );
        else
          constants.push(
            `static const ${type} ${name} = ${literal(value, type)};`,
          );
        return '';
      },
    )
    .replace(/^(?:in|out) float[234] \w+;$/gm, '')
    .replace(
      /\b(texture|textureLod|textureGrad|textureSize)\(/g,
      '$1(paperTextures, ',
    )
    .replace('void main()', '[mutating] void shade()');
  if (/\b(?:uniform|sampler2D|mat[34])\b/.test(body))
    throw new Error(
      'The Paper shader changed and needs a reviewed Kitty port.',
    );
  body = `
${kittyCompat}
${textureSource(textures, inlineTexture)}
struct PaperShader {
  ${textures.length ? 'PaperTextures paperTextures;' : ''}
  float u_time;
  float2 u_resolution;
  float2 v_objectUV, v_objectBoxSize, v_patternUV, v_patternBoxSize;
  float2 v_responsiveUV, v_responsiveBoxGivenSize, v_imageUV;
  float4 gl_FragCoord, fragColor;
${body}
};`;
  // Same object/pattern sizing as Paper 0.0.81's vertex shader, at pixel ratio 1.
  const fit = { none: 0, contain: 1, cover: 2 }[preset.fit];
  const source = `#language slang 2026
// Generated by Wallshader from Paper Shaders 0.0.81 (Apache-2.0).
// Adapted from GLSL to Slang with Kitty sizing, timing and terminal compositing.
// Paper copyright and notices accompany this file in LICENSE and NOTICE.
import kitty_custom_shader_types;
${constants.join('\n')}
${body}
float2 rotatePaper(float2 p, float r) {
  return float2(cos(r) * p.x - sin(r) * p.y, sin(r) * p.x + cos(r) * p.y);
}
float3 paperLinear(float3 c) {
  c = max(c, float3(0));
  return lerp(c / 12.92, pow((c + 0.055) / 1.055, float3(2.4)), step(float3(0.04045), c));
}
float4 paperFrame(float2 pos, float2 resolution, float timestamp, KittyTextures kitty) {
  float2 given = float2(${number(preset.worldWidth)}, ${number(preset.worldHeight)});
  given = float2(given.x == 0 ? resolution.x : max(1.0, given.x), given.y == 0 ? resolution.y : max(1.0, given.y));
  float2 origin = float2(${number(0.5 - preset.originX)}, ${number(preset.originY - 0.5)});
  float2 offset = float2(${number(-preset.offsetX)}, ${number(preset.offsetY)});
  float rotation = ${number((preset.rotation * Math.PI) / 180)};
  float scale = ${number(preset.scale)};
  int fit = ${fit};
  float objectSize = fit == 1 ? min(resolution.x, resolution.y) : fit == 2 ? max(resolution.x, resolution.y) : min(given.x, given.y);
  float2 objectScale = resolution / objectSize;
  PaperShader s;
  ${textures.length ? 's.paperTextures.kitty = kitty; s.paperTextures.resolution = resolution;' : ''}
  s.v_objectUV = rotatePaper(((pos - 0.5) * objectScale + origin * (objectScale - 1) + offset) / scale, rotation);
  float ratio = given.x / given.y;
  float noFitWidth = ratio * min(given.x / ratio, given.y);
  float width = fit == 1 ? ratio * min(resolution.x / ratio, resolution.y) : fit == 2 ? ratio * max(resolution.x / ratio, resolution.y) : noFitWidth;
  float2 patternScale = resolution / float2(width, width / ratio);
  float2 uv = (pos - 0.5 + offset / patternScale + origin - origin / patternScale) * resolution;
  if (fit > 0) uv *= noFitWidth / width;
  s.v_patternUV = (rotatePaper(uv / scale, rotation) + origin / patternScale - origin) * 0.01;
  s.u_resolution = resolution;
  s.v_objectBoxSize = float2(objectSize);
  s.v_patternBoxSize = float2(width, width / ratio);
  s.v_responsiveBoxGivenSize = given;
  float2 responsive = ((pos - 0.5) * patternScale + origin * (patternScale - 1) + offset) / scale;
  responsive.x *= ratio;
  responsive = rotatePaper(responsive, rotation);
  responsive.x /= ratio;
  s.v_responsiveUV = responsive;
  float imageRatio = ${number(values.u_imageAspectRatio)};
  float imageWidth = fit == 1 ? min(resolution.x / imageRatio, resolution.y) * imageRatio : fit == 2 ? max(resolution.x / imageRatio, resolution.y) * imageRatio : 10.0;
  float2 imageScale = resolution / float2(imageWidth, imageWidth / imageRatio);
  float2 imageUV = ((pos - 0.5) * imageScale + origin * (imageScale - 1) + offset) / scale;
  imageUV.x *= imageRatio;
  imageUV = rotatePaper(imageUV, rotation);
  imageUV.x /= imageRatio;
  imageUV += 0.5;
  imageUV.y = 1.0 - imageUV.y;
  s.v_imageUV = imageUV;
  s.gl_FragCoord = float4(pos * resolution, 0, 1);
  s.u_time = ${number(preset.frame / 1000)} + timestamp * ${number(preset.speed)};
  s.shade();
  return s.fragColor;
}
public float4 fragment_main(float4 color, KittyTextures t, KittyCustomShaderData d) {
  float4 result = paperFrame(t.pos, max(float2(d.viewport_size_pixels),float2(1)), d.timestamp, t);
  float3 terminal = color.a > 0.0 ? color.rgb : d.background.rgb;
  float3 globalDelta = abs(terminal - d.background.rgb);
  float3 activeDelta = abs(terminal - d.active_window_background.rgb);
  float distance = min(max(globalDelta.r, max(globalDelta.g, globalDelta.b)), max(activeDelta.r, max(activeDelta.g, activeDelta.b)));
  // Kitty can supply transparent background pixels when its dynamic opacity
  // is changed at runtime. The shader is the background in that case.
  float background = max(1 - smoothstep(0.02, 0.12, distance), 1 - saturate(color.a));
  float alpha = saturate(result.a);
  float3 rgb = paperLinear(result.rgb / max(0.00001, alpha));
  return float4(lerp(terminal, rgb, background * alpha * 0.35), max(color.a, background));
}
`;
  return {
    source,
    textures: assets,
    pipeline: `${assets.length ? `textures ${assets.map((_t, i) => (i === 0 ? 'a' : 'b')).join(' ')}\n` : ''}${assets.map((_t, i) => `startgroup\n    shaders wallshader-texture-${i}\n    output_texture ${i === 0 ? 'a' : 'b'}\nendgroup\n`).join('')}startgroup\n    animation_stop never\n    animation_step ${preset.speed === 0 || !/\bu_time\b/.test(glsl) ? 0 : fps === 60 ? 17 : 33}\n    shaders wallshader\nendgroup\n`,
  };
}
